### ISSUE TITLE
#US10 Configurar recordatorios de las tareas

### ISSUE THREAD

**Issue by nelsonvilte** [jnramos24/Ispc_Project#1]
Como usuario quiero quiero configurar recordatorios que me alerten antes de que las tareas venzan para poder evitar olvidos

**Comment by gaby720981** [comment]
[#32](https://github.com/jnramos24/ToDoOk/issues/32)

**Comment by gaby720981** [comment]
[#33](https://github.com/jnramos24/ToDoOk/issues/33)
