### ISSUE TITLE
#US08 Eliminar una tarea

### ISSUE THREAD

**Issue by nelsonvilte** [jnramos24/Ispc_Project#5]
Como Usuario con sesión iniciada Quiero poder eliminar una tarea.
- [x] Crear menu contextual

**Comment by gaby720981** [comment]
[#22](https://github.com/jnramos24/ToDoOk/issues/22)

**Comment by gaby720981** [comment]
[#23](https://github.com/jnramos24/ToDoOk/issues/23)

**Comment by gaby720981** [comment]
[#24](https://github.com/jnramos24/ToDoOk/issues/24)
