### ISSUE TITLE
#US11 Recibir notificaciones

### ISSUE THREAD

**Issue by nelsonvilte** [jnramos24/Ispc_Project#7]
Como usuario quiero recibir notificaciones en mi teléfono para poder recordar tareas pendientes o próximas fechas de vencimiento

**Comment by gaby720981** [comment]
[#34](https://github.com/jnramos24/ToDoOk/issues/34)

**Comment by gaby720981** [comment]
[#35](https://github.com/jnramos24/ToDoOk/issues/35)
